# Generated by Django 4.1.5 on 2023-01-11 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0002_rename_mensajes_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
