# Generated by Django 4.1.5 on 2023-01-12 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='mensaje',
            new_name='cuerpo',
        ),
    ]
