# Generated by Django 4.1.5 on 2023-01-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0008_mensaje_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='avatar',
        ),
    ]
