# Generated by Django 4.1.5 on 2023-01-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('edad', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('edad', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('anio', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('pais', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
            ],
        ),
    ]
