# Generated by Django 4.1.3 on 2022-12-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('vinculo', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('fechanac', models.DateField()),
            ],
        ),
    ]
