# Generated by Django 4.1.3 on 2022-12-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_rename_familiar_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('edad', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('edad', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('anio', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('pais', models.CharField(max_length=80)),
                ('director', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='persona',
        ),
    ]
