# Generated by Django 4.1.5 on 2023-01-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_actor_foto_director_foto_alter_pelicula_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='poster',
            field=models.ImageField(upload_to='posters'),
        ),
    ]
