# Generated by Django 4.1.5 on 2023-01-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_resenia_delete_posteo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resenia',
        ),
    ]
