# Generated by Django 4.1.5 on 2023-01-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_resenia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resenia',
        ),
    ]
