# Generated by Django 4.1.5 on 2023-01-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0016_actor_peliculas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='peliculas',
        ),
        migrations.AddField(
            model_name='actor',
            name='peliculashechas',
            field=models.ManyToManyField(related_name='actores', to='AppCoder.pelicula'),
        ),
    ]
