# Generated by Django 4.1.5 on 2023-01-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0019_remove_actor_peliculashechas'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='pelishechas',
            field=models.ManyToManyField(related_name='actores', to='AppCoder.pelicula'),
        ),
        migrations.AddField(
            model_name='director',
            name='pelishechas',
            field=models.ManyToManyField(related_name='directores', to='AppCoder.pelicula'),
        ),
    ]
