# Generated by Django 4.1.5 on 2023-01-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0021_pelicula_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='cast',
        ),
        migrations.AlterField(
            model_name='actor',
            name='pelishechas',
            field=models.ManyToManyField(related_name='pelishechasactores', to='AppCoder.pelicula'),
        ),
        migrations.AlterField(
            model_name='director',
            name='pelishechas',
            field=models.ManyToManyField(related_name='pelishechasdirectores', to='AppCoder.pelicula'),
        ),
    ]
