# Generated by Django 4.1.5 on 2023-01-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0022_remove_pelicula_cast_alter_actor_pelishechas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='cast',
            field=models.ManyToManyField(related_name='pelishechasactores', to='AppCoder.actor'),
        ),
    ]
