# Generated by Django 4.1.5 on 2023-01-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0024_alter_pelicula_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(max_length=200),
        ),
    ]
