# Generated by Django 4.1.5 on 2023-01-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0026_alter_director_pelishechas_remove_pelicula_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='pelishechasactores', to='AppCoder.actor'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='pelishechasdirector', to='AppCoder.director'),
        ),
    ]
