# Generated by Django 4.1.5 on 2023-01-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0027_alter_pelicula_cast_alter_pelicula_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='pelishechas',
            field=models.ManyToManyField(blank=True, related_name='pelishechasactores', to='AppCoder.pelicula'),
        ),
        migrations.AlterField(
            model_name='director',
            name='pelishechas',
            field=models.ManyToManyField(blank=True, related_name='pelishechasdirector', to='AppCoder.pelicula'),
        ),
    ]
